spring.application.name=Hibernate Entity Life Cycle
# PostgreSQL baglantisi
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Hibernate-in avtomatik cedvel yaratmasini söndürürük (Çünki Liquibase edecek)
spring.jpa.hibernate.ddl-auto=none

# SQL sorgularini konsolda görmek üçün (Lifecycle-? anlamaga kömek edir)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase-in ana faylinin yeri
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml